### ISSUE TITLE
fq1 is not None (rule align)

### ISSUE THREAD

**Issue by mgalland** [snakemake-workflows/rna-seq-star-deseq2#11]
Dear Snakemake lovers, 
I am giving a first try at the rna-seq-star-deseq2 pipeline with my own samples. 

`Traceback (most recent call last):
  File "/home/mgalland/rna-seq-star-deseq2/.snakemake/scripts/afy96dg4.wrapper.py", line 18, in <module>  
    assert fq1 is not None, "input-> fq1 is a required input parameter"  
AssertionError: input-> fq1 is a required input parameter
`  

When I look at the trimmed fastq file (fq1), it contains reads and amounts to 1.8Mb. So I don't really know what's going on there.  

Would there be a possibility to add test samples in order to run the pipeline fresh out of the box? 

Thank you
Marc

**Comment by sateeshperi** [comment]
@mgalland can you share your 'units.tsv' file and also the log generated by snakemake to see exactly where it is failing

**Comment by sateeshperi** [comment]
Also I don't think having test samples is a bad idea to run the pipeline and test installation. maybe @johanneskoester can comment on this ?

**Comment by johanneskoester** [comment]
The error comes from using a newer version of the star wrapper. The pipeline is designed to use version 0.19.4 of the wrapper. Did you change that version in any way?

**Comment by mgalland** [comment]
Thank you for your answers. 
I've given it another try with the 0.19.4 version of STAR. 
I have also downloaded test files from the ngs-test-data (Version 1.0.0) for the genome, annotation and transcriptome files so I get a reproducible example.

Here are my samples and units files. 
[samples.txt](https://github.com/snakemake-workflows/rna-seq-star-deseq2/files/2917029/samples.txt)
[units.txt](https://github.com/snakemake-workflows/rna-seq-star-deseq2/files/2917030/units.txt)

I now get another mistake (`ModuleNotFoundError: No module named 'pandas.core.internals.managers`) within the count_matrix rule. 

I am adding the complete log for debugging.  
[log.txt](https://github.com/snakemake-workflows/rna-seq-star-deseq2/files/2917032/log.txt)

Hope I'm contributing to make the pipeline more robust...
Cheers
Marc

**Comment by johanneskoester** [comment]
That bug was present in a previous version of Snakemake, but it should be fixed with the latest version of Snakemake and the pipeline. Can you confirm?

**Comment by mgalland** [comment]
I am running Snakemake version 5.4.3 with the .test data with the command `snakemake --use-conda` on my local machine. Here's what I get:

```
Activating conda environment: /Users/mgalland/Documents/workspace/rna-seq-star-deseq2/.snakemake/conda/e7ed19ef
Traceback (most recent call last):
  File "/Users/mgalland/Documents/workspace/rna-seq-star-deseq2/.snakemake/scripts/tmpejodow9z.wrapper.py", line 32, in <module>
    "STAR "
  File "/Users/mgalland/miniconda3/envs/snakemake/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  STAR --quantMode GeneCounts --sjdbGTFfile data/ref/annotation.chr21.gtf  --runThreadN 1 --genomeDir data/ref/index --readFilesIn trimmed/B-1.1.fastq.gz trimmed/B-1.2.fastq.gz --readFilesCommand zcat --outSAMtype BAM Unsorted --outFileNamePrefix star/B-1/ --outStd Log  > logs/star/B-1.log 2>&1' returned non-zero exit status 105.
[Thu Mar 21 17:21:35 2019]
Error in rule align:
    jobid: 6
    output: star/B-1/Aligned.out.bam, star/B-1/ReadsPerGene.out.tab
    log: logs/star/B-1.log
    conda-env: /Users/mgalland/Documents/workspace/rna-seq-star-deseq2/.snakemake/conda/e7ed19ef

RuleException:
CalledProcessError in line 27 of /Users/mgalland/Documents/workspace/rna-seq-star-deseq2/rules/align.smk:
Command 'source /Users/mgalland/miniconda3/bin/activate '/Users/mgalland/Documents/workspace/rna-seq-star-deseq2/.snakemake/conda/e7ed19ef'; set -euo pipefail;  /Users/mgalland/miniconda3/envs/snakemake/bin/python3.6 /Users/mgalland/Documents/workspace/rna-seq-star-deseq2/.snakemake/scripts/tmpejodow9z.wrapper.py' returned non-zero exit status 1.
  File "/Users/mgalland/Documents/workspace/rna-seq-star-deseq2/rules/align.smk", line 27, in __rule_align
  File "/Users/mgalland/miniconda3/envs/snakemake/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job align since they might be corrupted:
star/B-1/Aligned.out.bam
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by johanneskoester** [comment]
Better :-). Now, I suggest having a look at the log file of the failed rule: `logs/star/B-1.log`.

**Comment by dlaehnemann** [comment]
I'm closing this after a long period of inactivity. But please feel free to open new issues whenever more problems arise.
