### ISSUE TITLE
More a discussion point: Should trimming be made optional

### ISSUE THREAD

**Issue by sschmeier** [snakemake-workflows/rna-seq-star-deseq2#21]
I argue yes it should be optional. Trimming costs time and  often get better (or similar good) results with directly using STAR without trimming. 

Happy to make suggestions how to facilitate this. I have done it locally in my workflow by including different rule sets according to a flag in the config-file.

Seb

**Comment by johanneskoester** [comment]
Good point to consider. Yes, I would be happy to merge a PR that makes trimming optional. Technically, the best solution is to optionally (based on a config key) return the raw files [here](https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/eadda3b115b181ea3e83891d9da18081e48964b9/rules/align.smk#L1). This way, Snakemake will  simply not consider the trimming rules.

**Comment by sschmeier** [comment]
Has been integrated into the workflow.
