### ISSUE TITLE
Ubuntu 18.04.2 LTS - raise sp.CalledProcessError(retcode, cmd)

### ISSUE THREAD

**Issue by EasyPiPi** [snakemake-workflows/rna-seq-star-deseq2#24]
When I did the dry-run, the pipeline seems working, but when I run it, I got some errors related to star. The error is as followed:

Traceback (most recent call last):
  File "/home/yixin/Desktop/snakemake_workflow/rna-seq-star-deseq2-1.0.0/.snakemake/scripts/tmpqyit_18m.wrapper.py", line 32, in <module>
    "STAR "
  File "/home/yixin/.local/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  STAR --quantMode GeneCounts --sjdbGTFfile /home/yixin/Desktop/project_data/Ensembl/index/star/dmel/annotation.gtf  --runThreadN 4 --genomeDir /home/yixin/Desktop/project_data/Ensembl/index/star/dmel --readFilesIn trimmed/Dmel_control_1-rep2.fastq.gz --readFilesCommand zcat --outSAMtype BAM Unsorted --outFileNamePrefix star/Dmel_control_1-rep2/ --outStd Log  > logs/star/Dmel_control_1-rep2.log 2>&1' returned non-zero exit status 105.

Any hint will be highly appreciated.

**Comment by EasyPiPi** [comment]
It is also reproducible if I use the sample data, so it seems not to be data specific problem.

Traceback (most recent call last):
  File "/home/yixin/Desktop/snakemake_workflow/rna-seq-star-deseq2-1.0.0/.test/.snakemake/scripts/tmpg9n8flki.wrapper.py", line 32, in <module>
    "STAR "
  File "/home/yixin/.local/lib/python3.6/site-packages/snakemake/shell.py", line 149, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  STAR --quantMode GeneCounts --sjdbGTFfile data/ref/annotation.chr21.gtf  --runThreadN 4 --genomeDir data/ref/index --readFilesIn trimmed/B-1.1.fastq.gz trimmed/B-1.2.fastq.gz --readFilesCommand zcat --outSAMtype BAM Unsorted --outFileNamePrefix star/B-1/ --outStd Log  > logs/star/B-1.log 2>&1' returned non-zero exit status 105.

**Comment by johanneskoester** [comment]
You need to have a look at the log file. It is displayed in the error message, when it says `Error in rule:`

**Comment by EasyPiPi** [comment]
Thanks for the quick reply. I look into those log files, and they say:

Case 1:
EXITING because of FATAL ERROR: Genome version is INCOMPATIBLE with current STAR version
SOLUTION: please re-generate genome from scratch with the latest version of STAR

Case 2:
EXITING because of FATAL ERROR: could not open genome file data/ref/index/genomeParameters.txt
SOLUTION: check that the path to genome files, specified in --genomeDir is correct and the files are present, and have user read permsissions

For Case 1, I downloaded genome from https://useast.ensembl.org/Drosophila_melanogaster/Info/Index

For Case 2, I downloaded the sample data from https://github.com/snakemake-workflows/ngs-test-data/tree/89c605ca51bcabd8d7bf128d233c714e91c6b32a

I guess for Case 1 I did something wrong for building the genome index? And Case 2 I need to build the index myself?

**Comment by johanneskoester** [comment]
Yes indeed. Closing for now, since the error is not directly related to this pipeline.
