### ISSUE TITLE
snakemake version 5.9.1 raised an error with get_deseq2_threads called as a pointer

### ISSUE THREAD

**Issue by ginolhac** [snakemake-workflows/rna-seq-star-deseq2#26]
this line:
https://github.com/snakemake-workflows/rna-seq-star-deseq2/blob/a83f3013b44e92208ab88a8f1bce5080b3a42422/rules/diffexp.smk#L75

raised this error snakemake `version 5.9.1`

```
int() argument must be a string, a bytes-like object or a number, not 'function'
```

the error is not present with `version 5.5.1`

Replacing by  `threads: get_deseq2_threads()` silences the error

**Comment by dlaehnemann** [comment]
Closed by #62
