### ISSUE TITLE
count-matrix.py

### ISSUE THREAD

**Issue by sunhuaiyu** [snakemake-workflows/rna-seq-star-deseq2#32]
line#12 the groupby() operation could reorder columns, causing problem later when constructing the DESeqDataSet object.

**Comment by cbp44** [comment]
I ran into the same problem, PR #46 which I just submitted fixes the issue.

**Comment by cbp44** [comment]
This issue is fixed and merged into master (PR #60) and can now be closed.

**Comment by dlaehnemann** [comment]
I guess only the original poster or a maintainer can close this, so here I go. But in general, in such clear-cut cases, feel free to close such an issue if you have the permissions! Thanks again for keeping track of stuff!

**Comment by sunhuaiyu** [comment]
Thank you 👍
