### ISSUE TITLE
snakedeploy fails to deploy workflow

### ISSUE THREAD

**Issue by vkkodali** [snakemake-workflows/rna-seq-star-deseq2#34]
I am getting `TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'` when I try to deploy the rna-seq-star-deseq2 workflow as shown below: 
```
$ snakedeploy deploy-workflow https://github.com/snakemake-workflows/rna-seq-star-deseq2 . --tag v1.1.2 --force --verbose
Writing Snakefile with module definition...
Obtaining source repository...
Cloning into '.'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 548 (delta 22), reused 44 (delta 12), pack-reused 469
Receiving objects: 100% (548/548), 16.90 MiB | 0 bytes/s, done.
Resolving deltas: 100% (265/265), done.
Checking connectivity... done.
Writing template configuration...
Traceback (most recent call last):
  File "/home/kodalivk/.conda/envs/snakemake/bin/snakedeploy", line 10, in <module>
    sys.exit(main())
  File "/home/kodalivk/.conda/envs/snakemake/lib/python3.6/site-packages/snakedeploy/client.py", line 155, in main
    force=args.force,
  File "/home/kodalivk/.conda/envs/snakemake/lib/python3.6/site-packages/snakedeploy/deploy.py", line 62, in deploy
    shutil.copytree(config_dir, dest_config, dirs_exist_ok=force)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'
```
I do not have `mamba` so I used `conda` to install snakemake and snakedeploy as follows: 
```
$ conda create -c bioconda -c conda-forge --name snakemake snakemake snakedeploy
```

**Comment by kristianunger** [comment]
Hi there,

I also get an error when trying to deploy the workflow by:

`snakedeploy deploy-workflow https://github.com/snakemake-workflows/rna-seq-star-deseq2 . --tag v1.1.2`

I get the following errors:

(snakemake) [unger@frontser sm_rnaseq]$ snakedeploy deploy-workflow https://github.com/snakemake-workflows/rna-seq-star-deseq2 . --tag v1.1.2
Writing Snakefile with module definition...
Obtaining source repository...
Cloning into '.'...
remote: Enumerating objects: 548, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 548 (delta 22), reused 44 (delta 12), pack-reused 469
Receiving objects: 100% (548/548), 16.90 MiB | 13.14 MiB/s, done.
Resolving deltas: 100% (265/265), done.
Writing template configuration...
Traceback (most recent call last):
  File "/home/zyto/unger/miniconda3/envs/snakemake/bin/snakedeploy", line 10, in <module>
    sys.exit(main())
  File "/home/zyto/unger/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakedeploy/client.py", line 150, in main
    deploy(
  File "/home/zyto/unger/miniconda3/envs/snakemake/lib/python3.9/site-packages/snakedeploy/deploy.py", line 62, in deploy
    shutil.copytree(config_dir, dest_config, dirs_exist_ok=force)
  File "/home/zyto/unger/miniconda3/envs/snakemake/lib/python3.9/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/home/zyto/unger/miniconda3/envs/snakemake/lib/python3.9/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/project/sequencing/IBG/RNAseq_whole_HNSCC_2013_2016/sm_rnaseq/tmp/tmpvu25f5j5/config/samples.tsv', 'config/samples.tsv', "[Errno 13] Permission denied: 'config/samples.tsv'"), ('/project/sequencing/IBG/RNAseq_whole_HNSCC_2013_2016/sm_rnaseq/tmp/tmpvu25f5j5/config/config.yaml', 'config/config.yaml', "[Errno 13] Permission denied: 'config/config.yaml'"), ('/project/sequencing/IBG/RNAseq_whole_HNSCC_2013_2016/sm_rnaseq/tmp/tmpvu25f5j5/config/README.md', 'config/README.md', "[Errno 13] Permission denied: 'config/README.md'"), ('/project/sequencing/IBG/RNAseq_whole_HNSCC_2013_2016/sm_rnaseq/tmp/tmpvu25f5j5/config/units.tsv', 'config/units.tsv', "[Errno 13] Permission denied: 'config/units.tsv'"), (PosixPath('/project/sequencing/IBG/RNAseq_whole_HNSCC_2013_2016/sm_rnaseq/tmp/tmpvu25f5j5/config'), PosixPath('config'), "[Errno 13] Permission denied: 'config'")]

Any hints how to resolve this?

**Comment by mcortes-lopez** [comment]
I think it has to do with the python version, based on [this](https://stackoverflow.com/questions/63661976/problems-using-shutil-copytree-in-python) discussion. I tried installing snakedeploy under Python 3.8.3 and then it worked.

**Comment by dlaehnemann** [comment]
Thanks for looking into this, this had simply slipped through. I actually saw the same problem elsewhere back then and we solved it with an updated python dependency for the bioconda recipe of `snakedeploy`, see:
https://github.com/bioconda/bioconda-recipes/pull/28441

So this should have gone aways a few days after the original posts in this issue, and my recommendation would be to simply install the latest version of `snakedeploy` via bioconda (with the command by the original issue creator @vkkodali ).

So I hope this issue is solved, but feel free to reopen, if something similar comes up.
