### ISSUE TITLE
Confusion about the trimming for single-end data

### ISSUE THREAD

**Issue by john-lee-johnson** [snakemake-workflows/rna-seq-star-deseq2#4]
Hello,

I am new to snakemake and very eager to learn more.

I am trying to play with this workflow to learn more about how to properly use snakemake and I'm using data from GEO, I'm a little stuck on the trimming step. There are two rules, one for paired-end trimming, and one for single-end trimming. I have single-end data, but the paired-end trimming rule is only getting called. My units.tsv file looks like this:

sample | unit | fq1 | fq2
------------ | ------------- | ------------- | -------------
GSM945742 | SRR504812 | SRR504812.fastq
GSM945741 | SRR504810 | SRR504810.fastq
GSM945741 | SRR504811 | SRR504811.fastq

and the results of `snakemake -np` for one of the fastq files show that it's calling the paired-end rule. My question is, how can I make the workflow call the appropriate rule here?

```
rule cutadapt_pe:
    input: SRR504811.fastq
    output: trimmed/GSM945741-SRR504811.1.fastq.gz, trimmed/GSM945741-SRR504811.2.fastq.gz, trimmed/GSM945741-SRR504811.qc.txt
    log: logs/cutadapt/GSM945741-SRR504811.log
    jobid: 19
    wildcards: sample=GSM945741, unit=SRR504811
```

Thank you, I'm sorry if this is a dumb question

**Comment by johanneskoester** [comment]
Thanks for reporting. This might be a bug. Actually our test case only consists of paired end data. I will have a look tomorrow.

**Comment by johanneskoester** [comment]
This is now fixed in the master branch.
