### ISSUE TITLE
config.yaml defaults

### ISSUE THREAD

**Issue by neavemj** [snakemake-workflows/rna-seq-star-deseq2#43]
Good afternoon, thanks for the workflow!

In the default config.yaml on github, there is an example option like so:

config.yaml, line 37:   star: "--outSAMtype BAM Unsorted"

However, if left in the config file it causes an error because then the STAR step gets two "--outSAMtype" flags. I realise defaults are meant to be changed, but I don't think this particular example can ever be used (because the flag is already hard-coded into the workflow).

Thanks again!

Matt.

**Comment by dlaehnemann** [comment]
#41 will address this, so I'll try to follow up the problem there.
