### ISSUE TITLE
SyntaxError in line 14 of  Snakefile

### ISSUE THREAD

**Issue by Blosberg** [snakemake-workflows/rna-seq-star-deseq2#45]
Thanks for creating this package.
I've followed instructions [here](https://snakemake.github.io/snakemake-workflow-catalog/?usage=snakemake-workflows%2Frna-seq-star-deseq2) through to step 4, at which point when I try to run the workflow I get the following:

```
$snakemake --cores all -n
SyntaxError in line 14 of /path/to/workflow/Snakefile:
invalid syntax (Snakefile, line 14)
```

Line 14 being the `config:` line in the following context

```
...
module rna_seq_star_deseq2:
    snakefile:
        /path/to/workflow/Snakefile
    config:
        config
...
```
I can't see anything wrong with my config file. As far as I'm aware the packages from snakemake/deploy are all there. I also undid all of my project-specific entry data to the files in config and set them back to being identical to the original template.  Do you have any idea where this is coming from?

**Comment by dlaehnemann** [comment]
Were you able to solve this? If so, how? If not, maybe there was some other syntax problem in the `Snakefile`, that only gets thrown in line 14?

I'll close this issue for now, as it has aged quite a bit. But please feel free to reopen, if this persists (or to open another issue, if anything else comes up).
