### ISSUE TITLE
How to add quality control step (fastq_screen) to pipeline

### ISSUE THREAD

**Issue by john-lee-johnson** [snakemake-workflows/rna-seq-star-deseq2#5]
Hello, 

I've been trying to expand this pipeline as a means of learning how to use snakemake and I'm starting to understand it better, but I've been struggling with adding a quality control step (e.q., fastqc or fastq_screen). From my understanding, I think the problem is that the results of fastq_screen are "stand-alone" (i.e., they aren't intermediate files necessary for generating the final output in this case). I'm not entirely sure how to get snakemake to recognize that it needs to run this `fastq_screen` rule below on my fastq files (pre-trimmed in this case). I think it'll require adding something like the `qc/{sample}-{unit}.fastq_screen.txt` results to the `all` rule, but I can't get the wildcards to work correctly. Some help would be greatly appreciated! Thank you so much!

My Snakefile is:
```
shell.executable("bash")

configfile: "config.yaml"
samples = pd.read_table(config["samples"], index_col="sample")
units = pd.read_table(config["units"], index_col=["sample", "unit"], dtype=str)
units.index = units.index.set_levels([i.astype(str) for i in units.index.levels])  # enforce str in index


def is_single_end(sample, unit):
    return pd.isnull(units.loc[(sample, unit), "fq2"])

rule all:
    input:
        expand("results/diffexp/{contrast}.diffexp.tsv",
               contrast=config["diffexp"]["contrasts"]),
        "results/pca.svg",

def get_fastq(wildcards):
    return units.loc[(wildcards.sample, wildcards.unit), ["fq1", "fq2"]].dropna()

rule fastq_screen:
    input:
        get_fastq
    output:
        txt="qc/{sample}-{unit}.fastq_screen.txt",
        png="qc/{sample}-{unit}.fastq_screen.png"
    params:
        fastq_screen_config="{}".format(config["params"]["fastq_screen"]),
        subset=100000,
        aligner='bowtie2'
    threads: 8
    wrapper:
        "0.19.3/bio/fastq_screen"

include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/diffexp.smk"
```
When I run `snakemake -np` it doesn't seem to recognize that it needs to run fastq_screen, even if I try to use the `-R` option. How can I write the `all` rule so that it will also look for the fastq_screen results?
 
```
Job counts:
	count	jobs
	8	align
	1	all
	1	count_matrix
	8	cutadapt
	1	deseq2
	1	deseq2_init
	1	pca
	21

**Comment by johanneskoester** [comment]
You are almost there. All you need to do is:
```
rule all:
    input:
        expand("results/diffexp/{contrast}.diffexp.tsv",
               contrast=config["diffexp"]["contrasts"]),
        expand("qc/{unit.sample}-{unit.unit}.fastq_screen.png", unit=units.reset_index().itertuples()),
        "results/pca.svg",
```

Probably, QC should be a separate target though, such that you can run it first, before firing up the whole analysis. Hence, I would add it as a separate target rule:
```
rule qc:
    input:
        expand("qc/{unit.sample}-{unit.unit}.fastq_screen.png", unit=units.reset_index().itertuples())
```

Also, you should move the fastq_screen rule into a separate file under rules.

**Comment by john-lee-johnson** [comment]
That worked! Thank you for the quick reply!
