### ISSUE TITLE
Condition in samples.tsv is too specific

### ISSUE THREAD

**Issue by jonathandmoore** [snakemake-workflows/rna-seq-star-deseq2#53]
For a generic RNA-Seq pipeline, 'condition' is too specific, as a label for grouping samples. 

It may be that the user wants to make a comparison between sample groups from different genotypes, different timepoints, rather than different conditions or treatments.  'Group' would be a more generic label than 'Condition'.

**Comment by dlaehnemann** [comment]
Actually, some more thoughts from an internal discussion:

`explanatory variable` has a connotation of causality, that is problematic. So maybe not the best choice.

Something that speaks for `condition` is that it is commonly used in the field, e.g. see the [docs of DeSeq2](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) and the [docs of sleuth](https://pachterlab.github.io/sleuth_walkthroughs/pval_agg/analysis.html). What speaks against it from those sources, is that e.g. in the sleuth docs, `condition` is also used for confounding variables / uninteresting covariates that are simply modeled to exclude their effect from the final differential expression test.

To a certain extent, these docs also speak for the use of `group` in this context, as they do make use of this word to describe the categories in a variable of interest.

However, this last thought brings me to a candidate that might be more suitable: `variable_of_interest`
This can also encompass continuous-valued variables, as opposed to only categorical values. And e.g. DeSeq2 can model such a continuouas-valued variable of interest. And makes use of the term "variable of interest" in the documentation. So after some more thought, this is my new favourite candidate. But I'm glad to hear more suggestions!

**Comment by jonathandmoore** [comment]
variable_of_interest seems a good fit.

**Comment by johanneskoester** [comment]
I think the true solution is to just require people to specify a design matrix (via a formula over column names) instead of naming one column in a predefined way. We should modify the workflow accordingly. Our bandwidth is limited at the moment, so that I cannot promise this to happen immediately, and any PR would be welcome.

**Comment by svenrahmann** [comment]
While formulas are a good general solution, I think there should be an alternative (simple) way to pick one "class label" column with no need to worry about a possible bias term and formula syntax.

**Comment by dlaehnemann** [comment]
> I think the true solution is to just require people to specify a design matrix (via a formula over column names) instead of naming one column in a predefined way. We should modify the workflow accordingly. Our bandwidth is limited at the moment, so that I cannot promise this to happen immediately, and any PR would be welcome.

Obviously, it wasn't as simple as that. One does not simply `specify a design matrix`.

But there's an attempt to side-step this naming issue in the spirit of what @johanneskoester suggested, here. It generalizes the configuration of the `DESeq2` differential analysis, hopefully explaining all the options clear enough righ there in the `config.yaml` file. And as a plus, it does use the wording `variable_of_interest` as a meta entry key.

@jonathandmoore, it's been a while. But maybe you're still up for a review? If so, please head over to PR #66.
