### ISSUE TITLE
AttributeError: module 'sqlite3' has no attribute 'OptimizedUnicode'

### ISSUE THREAD

**Issue by hmkim** [snakemake-workflows/rna-seq-star-deseq2#68]
<img width="1149" alt="Screenshot 2023-10-24 at 5 36 43 PM" src="https://github.com/snakemake-workflows/rna-seq-star-deseq2/assets/4966343/9ccb4fef-741c-4999-937f-0f89312bc6ef">

https://github.com/daler/gffutils/pull/221

You need to change the dependency version of gffutils to 0.12.

**Comment by dlaehnemann** [comment]
Many thanks for the report and the suggested solution, I'll look through this right away! For posting code / verbatim error messages here on GitHub, I recommend using [MarkDown code block syntax](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). This makes them much more readable, and also searchable.

**Comment by dlaehnemann** [comment]
Closed by #69 , many thanks again for tracking this down.
