### ISSUE TITLE
base_level and level_of_interest in example config.yaml

### ISSUE THREAD

**Issue by keksundso** [snakemake-workflows/rna-seq-star-deseq2#73]
In the _diffexp_ section of the example _config.yaml_ the two variables _base_level_ and _level_of_interest_ are set to A, B, and C, which are the sample names defined in _samples.tsv_. 

However, shouldn't the level refer to the treatment_# column of _samples.tsv_, thus in the example files 'treated' or 'untreated'. (e.g. like in the _.test/configs_)

**Comment by dlaehnemann** [comment]
Thanks for reporting this and sorry, if this caused confusion in the setup.

I updated the example `config/config.yaml` accordingly. But do feel free to double-check that everything is correct now. :sweat_smile:
